export default {
  condition: 'location contain http at 0',
  resource: {
    'sprite/bandit_0.png': '//lh4.googleusercontent.com/-7xAYm5GpA4k/UWf0qug24QI/AAAAAAAAAJo/NFWjW_yI5xM/s800/bandit_0.png',
    'sprite/bandit_0_mirror.png': '//lh3.googleusercontent.com/-kiwO55hkzVI/UWf0rN2vXTI/AAAAAAAAAJw/ReUm3Hb6Mk8/s800/bandit_0_mirror.png',
    'sprite/bandit_1.png': '//lh4.googleusercontent.com/-xWKYeAFTSgA/UWf0rv9quyI/AAAAAAAAAJ4/g4UlwGNXKCY/s800/bandit_1.png',
    'sprite/bandit_1_mirror.png': '//lh6.googleusercontent.com/-lftXly43qlo/UWf0sGzAvsI/AAAAAAAAAKA/4Fbii5C_reo/s800/bandit_1_mirror.png',
    'sprite/bandit_f.png': '//lh5.googleusercontent.com/-NKH8hJph-hg/Ur8Ow9V13PI/AAAAAAAAAR8/CaVWiYe18Og/s120-no/bandit_f.png',
    'sprite/bandit_s.png': '//lh4.googleusercontent.com/--1n5FohdmZs/Ur8Ow0F_YfI/AAAAAAAAAR4/Kihrrzzf2lM/w40-h45-no/bandit_s.png',

    'sprite/deep_0.png': '//lh4.googleusercontent.com/-ipF3Xtk1TZU/UWf0s7JtGAI/AAAAAAAAAKI/x9zPXLnCNlg/s800/deep_0.png',
    'sprite/deep_0_mirror.png': '//lh5.googleusercontent.com/--FLC3nEl8MM/UWf0tTLmicI/AAAAAAAAAKQ/arrpKPAmdlM/s800/deep_0_mirror.png',
    'sprite/deep_1.png': '//lh3.googleusercontent.com/-kAIrvbjwtFY/UWf0uMQPdSI/AAAAAAAAAKY/1MxMFvXfTPM/s800/deep_1.png',
    'sprite/deep_1_mirror.png': '//lh3.googleusercontent.com/-eKfj7XoOx0c/UWf0upednhI/AAAAAAAAAKg/FJEGF5l8h6M/s800/deep_1_mirror.png',
    'sprite/deep_2.png': '//lh3.googleusercontent.com/-5AP2I5zPpNU/UWf0u5forHI/AAAAAAAAAKo/lUO2siV-C7Y/s800/deep_2.png',
    'sprite/deep_2_mirror.png': '//lh4.googleusercontent.com/-0eCb4Spllcg/UWf0vTMdDhI/AAAAAAAAAK0/oM3S-z0jms8/s800/deep_2_mirror.png',
    'sprite/deep_ball.png': '//lh5.googleusercontent.com/-VjTtg8Ub0nw/UWf0vevHrKI/AAAAAAAAAMQ/BkH1H0kiMSc/s328/deep_ball.png',
    'sprite/deep_ball_mirror.png': '//lh4.googleusercontent.com/-HC4Iww9n-P0/UWf0wDhd-aI/AAAAAAAAALA/mbUqnXZS6mc/s328/deep_ball_mirror.png',
    'sprite/deep_f.png': '//lh6.googleusercontent.com/-h30GMQ39L-k/Ur8Oxl799PI/AAAAAAAAASU/IGyri87_ZYs/s120-no/deep_f.png',
    'sprite/deep_s.png': '//lh6.googleusercontent.com/-6vh-sCXDG48/Ur8OyfS7VsI/AAAAAAAAASc/NAgi4YPSqQk/w40-h45-no/deep_s.png',

    'sprite/davis_0.png': '//lh6.googleusercontent.com/-F1bzmSBob10/Ur8QoTPtjbI/AAAAAAAAATg/XfBmh5u-_DY/w800-h560-no/davis_0.png',
    'sprite/davis_1.png': '//lh5.googleusercontent.com/-AYU8RV2WnMg/Ur8QocgWWmI/AAAAAAAAATU/MXcVfp4-gqA/w800-h560-no/davis_1.png',
    'sprite/davis_2.png': '//lh6.googleusercontent.com/-1C5XHb-X1TE/Ur8QoeNFkEI/AAAAAAAAATY/c5b5Fp2-cfU/w800-h340-no/davis_2.png',
    'sprite/davis_ball.png': '//lh4.googleusercontent.com/-7B5UkrZvaMg/Ur8QpKZE6uI/AAAAAAAAATk/y4--hs6g74E/w328-h141-no/davis_ball.png',
    'sprite/davis_f.png': '//lh3.googleusercontent.com/-EN2Ej4JKfXo/Ur8Ow9gJSWI/AAAAAAAAASQ/fxIlfSWsNv8/s120-no/davis_f.png',
    'sprite/davis_s.png': '//lh3.googleusercontent.com/-far3jVWpf5Q/Ur8OxTpiENI/AAAAAAAAASM/_0GJ7b0WWyw/w40-h45-no/davis_s.png',

    'sprite/effect0.png': '//lh3.googleusercontent.com/-S1rrx4z-yJk/UWf0wZKDpUI/AAAAAAAAALI/fu3tNg1NrYI/s612/effect0.png',
    'sprite/effect0_mirror.png': '//lh3.googleusercontent.com/-PM4Gwblarks/UWf0wgbw46I/AAAAAAAAAMc/6qV-yqoC0vc/s612/effect0_mirror.png',
    'sprite/broken.png': '//lh4.googleusercontent.com/-X-5fCkVvoHI/Ur8QEeZki1I/AAAAAAAAAS8/bBzECuWE95g/s300-no/broken.png',
    'sprite/broken2.png': '//lh3.googleusercontent.com/-RPzZ0L7vRUg/Ur8QEUNeYvI/AAAAAAAAAS4/0lKvvTJVFRo/w281-h152-no/broken2.png',

    'sprite/weapon0.png': '//lh4.googleusercontent.com/-G-Exzp5HhGk/UWf0w5F-LyI/AAAAAAAAALY/feEunojO0cw/s490/weapon0.png',
    'sprite/weapon0_mirror.png': '//lh6.googleusercontent.com/-MgpHgMiV3e4/UWf0ww_-l6I/AAAAAAAAALk/o9c2PyDgL0Q/s490/weapon0_mirror.png',
    'sprite/weapon1.png': '//lh6.googleusercontent.com/-QzGncxvfx_o/UWf0xYzznyI/AAAAAAAAALc/vObqCnjTpVg/s455/weapon1.png',
    'sprite/weapon1_mirror.png': '//lh6.googleusercontent.com/-ztQh3aA6u50/UWf0xmWsSmI/AAAAAAAAAMI/NHnkE0b975M/s455/weapon1_mirror.png',
    'sprite/weapon2.png': '//lh3.googleusercontent.com/-sZgZiSUOuWM/UWf0yM6yCMI/AAAAAAAAALw/dmrs2MakO9E/s490/weapon2.png',
    'sprite/weapon2_mirror.png': '//lh4.googleusercontent.com/-GHMZd6DTBqU/UWf0yEtjiSI/AAAAAAAAAL4/CMUUJ4dGnRQ/s490/weapon2_mirror.png',
    'sprite/weapon3.png': '//lh4.googleusercontent.com/-Gjt9lUagcCo/UWf0yUFBHOI/AAAAAAAAAMA/aLZ25ruBMPk/s455/weapon3.png',
    'sprite/weapon3_mirror.png': '//lh3.googleusercontent.com/-L77sU6tkh48/UWf0yh611UI/AAAAAAAAAME/NftmrhiUico/s455/weapon3_mirror.png',

    'bg/cuhk/s.png': '//lh5.googleusercontent.com/-K9nSdHGO33Y/UkLPUC0y3RI/AAAAAAAAAQc/nUubvLZN43M/w37-h9-no/s.png',
    'bg/cuhk/floor1.png': '//lh3.googleusercontent.com/-w9uR8F2rJ0s/UkLPQM53fzI/AAAAAAAAAPE/JazY2MZTfp0/w797-h29-no/floor1.png',
    'bg/cuhk/floor2.png': '//lh3.googleusercontent.com/-REmAXSWpyJ4/UkLPQUfTJcI/AAAAAAAAAPM/t7sLmE4BeJE/w797-h31-no/floor2.png',
    'bg/cuhk/floor3.png': '//lh4.googleusercontent.com/-bktPpeeeOCw/UkLPQwCYNWI/AAAAAAAAAPU/ofwJ2aMdxz8/w800-h106-no/floor3.png',
    'bg/cuhk/sky1.png': '//lh5.googleusercontent.com/-weNLZohEym8/UkLPUmYkAWI/AAAAAAAAAQ4/HhN1YIYFyZc/w800-h210-no/sky1.png',
    'bg/cuhk/sky2.png': '//lh3.googleusercontent.com/-eQyM9IoE32I/UkLPUlDYqyI/AAAAAAAAAQs/PBv3rYMIixk/w167-h210-no/sky2.png',
    'bg/cuhk/a1.png': '//lh5.googleusercontent.com/-dDx7K3hmJm8/UkLPPmJpHFI/AAAAAAAAAO0/jw3Fpf9wGl4/w130-h68-no/a1.png',
    'bg/cuhk/a2.png': '//lh6.googleusercontent.com/-k-zEr5ER3FI/UkLPPl-bdSI/AAAAAAAAAQg/ekteGbERGjU/w190-h106-no/a2.png',
    'bg/cuhk/lib.png': '//lh6.googleusercontent.com/-fJ33Wu3vM64/UkLPTbHdq-I/AAAAAAAAAQM/dBdnejHuTr4/w641-h232-no/lib.png',
    'bg/cuhk/hill.png': '//lh5.googleusercontent.com/-9yHdsNZFeLk/UkLPR05p1xI/AAAAAAAAAPs/kXWOpovQtWY/w313-h264-no/hill.png',
    'bg/cuhk/hill2.png': '//lh6.googleusercontent.com/-e0VOCI4muDY/UkLPSMrt81I/AAAAAAAAAP0/-m6shgXVfYQ/w220-h119-no/hill2.png',
    'bg/cuhk/bu1.png': '//lh3.googleusercontent.com/-4iq7NyBhUb8/UkLPPiNgn-I/AAAAAAAAAO8/xlFIZGCOoZ8/w349-h212-no/bu1.png',
    'bg/cuhk/statue.png': '//lh5.googleusercontent.com/--d3tFdp3JIM/UkLPU4zzypI/AAAAAAAAAQ0/p1xSpv8kaCo/w407-h110-no/statue.png',
    'bg/cuhk/lamp1.png': '//lh5.googleusercontent.com/-nPKgatul6XU/UkLPSp1C7II/AAAAAAAAAP8/OvWkLbScouQ/w82-h137-no/lamp1.png',
    'bg/cuhk/lamp2.png': '//lh3.googleusercontent.com/-v5YXfqz_Gv4/UkLPS3clFII/AAAAAAAAAQA/f0PzZU2ZTTs/w82-h137-no/lamp2.png',
    'bg/cuhk/grass2.png': '//lh4.googleusercontent.com/-9reyLWxSMSY/UkLPRVEsUxI/AAAAAAAAAPg/AUaxFwwvxgs/w163-h54-no/grass2.png',
    'bg/cuhk/grass.png': '//lh5.googleusercontent.com/-pT0H5SRl8Tc/UkLPRORhBAI/AAAAAAAAAPc/lMi3f47IJos/w180-h128-no/grass.png',
    'bg/cuhk/right.png': '//lh3.googleusercontent.com/-XhOUV4xYvRE/UkLPTnq8iKI/AAAAAAAAAQU/LggQlqUzjsI/w141-h122-no/right.png',

    'bg/ft/c1.png': '//lh5.googleusercontent.com/-Q8fLWterqj8/Ur8R6veZW-I/AAAAAAAAAT8/zakdICjmO6A/w54-h134-no/c1.png',
    'bg/ft/c2.png': '//lh4.googleusercontent.com/-TJpeHaY_Whs/Ur8R6qRM54I/AAAAAAAAAUc/gxl6XWShRjs/w60-h43-no/c2.png',
    'bg/ft/f1.png': '//lh4.googleusercontent.com/-kWR0WigtfA4/Ur8R66bhcGI/AAAAAAAAAUA/i6R-KrJ4NCI/w54-h77-no/f1.png',
    'bg/ft/f2.png': '//lh4.googleusercontent.com/-fimGtMwhSdg/Ur8R7Qr3woI/AAAAAAAAAUE/ZXZvA7jUU_8/w54-h77-no/f2.png',
    'bg/ft/f3.png': '//lh3.googleusercontent.com/-kNKZnvr227E/Ur8R7f1CGmI/AAAAAAAAAUU/aDJyLw9ulWQ/w54-h77-no/f3.png',
    'bg/ft/f4.png': '//lh5.googleusercontent.com/-W7ouP3DqtVo/Ur8R7zmeDPI/AAAAAAAAAUY/hQfpFYODeyk/w54-h77-no/f4.png',
    'bg/ft/f5.png': '//lh3.googleusercontent.com/-X71MzAxbx4M/Ur8R8boyezI/AAAAAAAAAU0/jMOypqMqOgs/w54-h77-no/f5.png',
    'bg/ft/f6.png': '//lh6.googleusercontent.com/-ZgVdtFym8HE/Ur8R8hZIJ4I/AAAAAAAAAUw/lQQeuOTfUtE/w54-h77-no/f6.png',
    'bg/ft/f7.png': '//lh4.googleusercontent.com/-wa9n_Amf7GA/Ur8R8udupEI/AAAAAAAAAUs/V_c5cKgs3hY/w54-h77-no/f7.png',
    'bg/ft/f8.png': '//lh4.googleusercontent.com/-DiXTf0pwsms/Ur8R9Z0zlaI/AAAAAAAAAVM/drPnd1_jy-Q/w54-h77-no/f8.png',
    'bg/ft/f9.png': '//lh6.googleusercontent.com/-_tJ1HDAqx-o/Ur8R9m9QF0I/AAAAAAAAAVI/u-jexPR46pc/w54-h77-no/f9.png',
    'bg/ft/fa.png': '//lh3.googleusercontent.com/-iiHpdudirn8/Ur8R91lQ7_I/AAAAAAAAAVE/y3CMixajz1g/w54-h77-no/fa.png',
    'bg/ft/fb.png': '//lh6.googleusercontent.com/-hMOYaCpQr2Q/Ur8R-TDBejI/AAAAAAAAAVk/E-3XvEitWiw/w54-h77-no/fb.png',
    'bg/ft/fc.png': '//lh5.googleusercontent.com/-HGnJtgGth6I/Ur8R-ub7mWI/AAAAAAAAAVc/S1lRQfUBnRM/w54-h77-no/fc.png',
    'bg/ft/fd.png': '//lh6.googleusercontent.com/-MJsJtUfBwps/Ur8R-yaX5gI/AAAAAAAAAVg/P7ZT8Sy4PEM/w54-h77-no/fd.png',
    'bg/ft/g1.png': '//lh6.googleusercontent.com/-McFliJkpOK0/Ur8R_pU0ueI/AAAAAAAAAWM/qklECwn9dCo/w162-h59-no/g1.png',
    'bg/ft/g2.png': '//lh4.googleusercontent.com/-yI0aevjaOvQ/Ur8R_rig56I/AAAAAAAAAV0/yZVAHgj_JRs/w140-h11-no/g2.png',
    'bg/ft/g3.png': '//lh4.googleusercontent.com/-MeN7WyNuJ_w/Ur8R_yW-mII/AAAAAAAAAVw/m5Yo5zp9uoI/w140-h12-no/g3.png',
    'bg/ft/g4.png': '//lh5.googleusercontent.com/-N7rJUkuwoqA/Ur8SAoagLYI/AAAAAAAAAWI/D1gOyY_F2iA/w128-h21-no/g4.png',
    'bg/ft/s.png': '//lh5.googleusercontent.com/-SvpG_Cy8_sU/Ur8SA3JaAvI/AAAAAAAAAWE/EEr8ouFJWtg/w37-h9-no/s.png',
    'bg/ft/sky.png': '//lh6.googleusercontent.com/-SxBbr2S14TM/Ur8SBm0B3II/AAAAAAAAAWo/NKcb2nDP7_0/w797-h74-no/sky.png',
    'bg/ft/w1.png': '//lh5.googleusercontent.com/-op262Nyzrq0/Ur8SBulXVPI/AAAAAAAAAWg/I8OYCIU_qxQ/w144-h31-no/w1.png',
    'bg/ft/w2.png': '//lh5.googleusercontent.com/-d57Wb0BFQwU/Ur8SB2tJxlI/AAAAAAAAAWc/YI6mZ5kYLDw/w24-h57-no/w2.png',
    'bg/ft/w3.png': '//lh3.googleusercontent.com/--iML7PvQTCw/Ur8SCuRck7I/AAAAAAAAAWs/WfXIDVp21is/w144-h30-no/w3.png',
    'UI/frontpage.png': '//lh3.googleusercontent.com/hztVuGrRPelFUZrHhOOGmrYIXMofFRz11vsJVnTWrks=w794-h550-no',
    'UI/character_selection.png': '//lh3.googleusercontent.com/nuctp_KWPrtf_6YiN-zVwtvP86vhShxpKmjM-ZULgxg=w794-h550-no',
    'UI/settings.png': '//lh3.googleusercontent.com/oCnZgQ7W18C9Ku1Odpg5IHfc3fDx5bGQu839YX-l6SU=w794-h546-no',
    'sprite/firen_0.png': '//1.bp.blogspot.com/-ve6J4VQVsLk/WV_jSQVSc9I/AAAAAAAAAb0/SRKy0b3hJ98yO6G-K1xAL75O0DneKzJXACKgBGAs/s1600/firen_0.png',
    'sprite/firen_1.png': '//1.bp.blogspot.com/-mIvoHaywjIQ/WV_jSaJd2MI/AAAAAAAAAb0/LepoqvRYfgMobVmH-sJKjAu8ZZ6WCcuMQCKgBGAs/s1600/firen_1.png',
    'sprite/firen_2.png': '//2.bp.blogspot.com/-F4Hypwq3C3I/WV_jSY5P_XI/AAAAAAAAAb0/3WYxppAzt9sxT72-VOIE-f7-c6dB6Vv5ACKgBGAs/s1600/firen_2.png',
    'sprite/firen_ball.png': '//1.bp.blogspot.com/-mgViujy3ppE/WV_jSYusLjI/AAAAAAAAAb0/cGGMjlmh_GQ7F1QT5bDYrlCFM7__y0jogCKgBGAs/s1600/firen_ball.png',
    'sprite/firen_f.png': '//2.bp.blogspot.com/-1DjfudxKtSs/WV_jSVgMxtI/AAAAAAAAAb0/8YJ3V2SPFb0kad8nyuMIxtUrPQvfueFTACKgBGAs/s1600/firen_f.png',
    'sprite/john_0.png': '//1.bp.blogspot.com/-0TeyMLnj014/WV_lL4uy2KI/AAAAAAAAAcU/9blvQPlLCd07YL5nrcLGHY8_CJb77V9bACKgBGAs/s1600/john_0.png',
    'sprite/john_f.png': '//1.bp.blogspot.com/--Hp1BvG-J7k/WV_lL9c5C1I/AAAAAAAAAcU/4mFylE1G388uDqV8sqbpeZKxRnUWbStiwCKgBGAs/s1600/john_f.png',
    'sprite/john_s.png': '//3.bp.blogspot.com/-1kk45Nbp3EI/WV_lL9M8_aI/AAAAAAAAAcU/DJ-jiyfYaoU8rUniRUqjfe5y9PT94su3gCKgBGAs/s1600/john_s.png',

    'sprite/john_1.png': 'sprite/john_1.png',
    'sprite/john_2.png': 'sprite/john_2.png',
    'sprite/john_3.png': 'sprite/john_3.png',
    'sprite/john_ball.png': 'sprite/john_ball.png',
    'sprite/john_ball2.png': 'sprite/john_ball2.png',
    'sprite/john_biscuit.png': 'sprite/john_biscuit.png',
    'sprite/john_col.png': 'sprite/john_col.png',
    'sprite/john_col2.png': 'sprite/john_col2.png',
    'sprite/john_col3.png': 'sprite/john_col3.png',

    'sprite/dennis_0.png': 'sprite/dennis_0.png',
    'sprite/dennis_1.png': 'sprite/dennis_1.png',
    'sprite/dennis_2.png': 'sprite/dennis_2.png',
    'sprite/dennis_3.png': 'sprite/dennis_3.png',
    'sprite/dennis_ball.png': 'sprite/dennis_ball.png',
    'sprite/dennis_ball2.png': 'sprite/dennis_ball2.png',
    'sprite/dennis_ball3.png': 'sprite/dennis_ball3.png',
    'sprite/dennis_chase.png': 'sprite/dennis_chase.png',
    'sprite/dennis_f.png': 'sprite/dennis_f.png',
    'sprite/dennis_s.png': 'sprite/dennis_s.png',

    'sprite/henry_0.png': 'sprite/henry_0.png',
    'sprite/henry_1.png': 'sprite/henry_1.png',
    'sprite/henry_2.png': 'sprite/henry_2.png',
    'sprite/henry_arrow1.png': 'sprite/henry_arrow1.png',
    'sprite/henry_arrow2.png': 'sprite/henry_arrow2.png',
    'sprite/henry_arrow3.png': 'sprite/henry_arrow3.png',
    'sprite/henry_arrow4.png': 'sprite/henry_arrow4.png',
    'sprite/henry_wind.png': 'sprite/henry_wind.png',
    'sprite/henry_f.png': 'sprite/henry_f.png',
    'sprite/henry_s.png': 'sprite/henry_s.png',

    'sprite/firen_ball2.png': 'sprite/firen_ball2.png',
    'sprite/firen_chase.png': 'sprite/firen_chase.png',
    'sprite/firen_col.png': 'sprite/firen_col.png',
    'sprite/firen_col2.png': 'sprite/firen_col2.png',
    'sprite/firen_exp.png': 'sprite/firen_exp.png',
    'sprite/firen_flame.png': 'sprite/firen_flame.png',
    'sprite/firen_grd.png': 'sprite/firen_grd.png',
    'sprite/firen_s.png': 'sprite/firen_s.png',

    'sprite/freeze_0.png': 'sprite/freeze_0.png',
    'sprite/freeze_1.png': 'sprite/freeze_1.png',
    'sprite/freeze_2.png': 'sprite/freeze_2.png',
    'sprite/freeze_ball.png': 'sprite/freeze_ball.png',
    'sprite/freeze_ball2.png': 'sprite/freeze_ball2.png',
    'sprite/freeze_chase.png': 'sprite/freeze_chase.png',
    'sprite/freeze_col.png': 'sprite/freeze_col.png',
    'sprite/freeze_col2.png': 'sprite/freeze_col2.png',
    'sprite/freeze_ww.png': 'sprite/freeze_ww.png',
    'sprite/freeze_f.png': 'sprite/freeze_f.png',
    'sprite/freeze_s.png': 'sprite/freeze_s.png',

    'sprite/louis_0.png': 'sprite/louis_0.png',
    'sprite/louis_1.png': 'sprite/louis_1.png',
    'sprite/louis_2.png': 'sprite/louis_2.png',
    'sprite/louis_3.png': 'sprite/louis_3.png',
    'sprite/louis_ball.png': 'sprite/louis_ball.png',
    'sprite/louis_f.png': 'sprite/louis_f.png',
    'sprite/louis_s.png': 'sprite/louis_s.png',

    'sprite/rudolf_0.png': 'sprite/rudolf_0.png',
    'sprite/rudolf_1.png': 'sprite/rudolf_1.png',
    'sprite/rudolf_2.png': 'sprite/rudolf_2.png',
    'sprite/rudolf_3.png': 'sprite/rudolf_3.png',
    'sprite/rudolf_flash.png': 'sprite/rudolf_flash.png',
    'sprite/rudolf_flash2.png': 'sprite/rudolf_flash2.png',
    'sprite/rudolf_smoke.png': 'sprite/rudolf_smoke.png',
    'sprite/rudolf_weapon.png': 'sprite/rudolf_weapon.png',
    'sprite/rudolf_f.png': 'sprite/rudolf_f.png',
    'sprite/rudolf_s.png': 'sprite/rudolf_s.png',

    'sprite/bandit_0b.png': 'sprite/bandit_0b.png',
    'sprite/bandit_1b.png': 'sprite/bandit_1b.png',
    'sprite/bandit_col.png': 'sprite/bandit_col.png',
    'sprite/bandit_col2.png': 'sprite/bandit_col2.png',
    'sprite/bandit_fb.png': 'sprite/bandit_fb.png',
    'sprite/bandit_flame.png': 'sprite/bandit_flame.png',
    'sprite/bandit_sb.png': 'sprite/bandit_sb.png',
    'sprite/bandit_shadow.png': 'sprite/bandit_shadow.png',

    'sprite/davis_ball2.png': 'sprite/davis_ball2.png',
    'sprite/davis_col.png': 'sprite/davis_col.png',

    'sprite/deep_3.png': 'sprite/deep_3.png',
    'sprite/deep_4.png': 'sprite/deep_4.png',
    'sprite/deep_ball2.png': 'sprite/deep_ball2.png',
    'sprite/deep_ball3.png': 'sprite/deep_ball3.png',
    'sprite/deep_ball4.png': 'sprite/deep_ball4.png',
    'sprite/deep_ball5.png': 'sprite/deep_ball5.png',
    'sprite/deep_ball6.png': 'sprite/deep_ball6.png',
    'sprite/deep_ball7.png': 'sprite/deep_ball7.png',

    'sprite/knight_0.png': 'sprite/knight_0.png',
    'sprite/knight_0b.png': 'sprite/knight_0b.png',
    'sprite/knight_1.png': 'sprite/knight_1.png',
    'sprite/knight_1b.png': 'sprite/knight_1b.png',
    'sprite/knight_2.png': 'sprite/knight_2.png',
    'sprite/knight_2b.png': 'sprite/knight_2b.png',
    'sprite/knight_ball.png': 'sprite/knight_ball.png',
    'sprite/knight_col.png': 'sprite/knight_col.png',
    'sprite/knight_f.png': 'sprite/knight_f.png',
    'sprite/knight_s.png': 'sprite/knight_s.png',

    'sprite/woody_0.png': 'sprite/woody_0.png',
    'sprite/woody_1.png': 'sprite/woody_1.png',
    'sprite/woody_2.png': 'sprite/woody_2.png',
    'sprite/woody_3.png': 'sprite/woody_3.png',
    'sprite/woody_ball.png': 'sprite/woody_ball.png',
    'sprite/woody_f.png': 'sprite/woody_f.png',
    'sprite/woody_s.png': 'sprite/woody_s.png',

    'sprite/julian_0.png': 'sprite/julian_0.png',
    'sprite/julian_1.png': 'sprite/julian_1.png',
    'sprite/julian_2.png': 'sprite/julian_2.png',
    'sprite/julian_ball.png': 'sprite/julian_ball.png',
    'sprite/julian_ball2.png': 'sprite/julian_ball2.png',
    'sprite/julian_col.png': 'sprite/julian_col.png',
    'sprite/julian_col2.png': 'sprite/julian_col2.png',
    'sprite/julian_exp.png': 'sprite/julian_exp.png',
    'sprite/julian_f.png': 'sprite/julian_f.png',
    'sprite/julian_s.png': 'sprite/julian_s.png',

    'sprite/jan_0.png': 'sprite/jan_0.png',
    'sprite/jan_1.png': 'sprite/jan_1.png',
    'sprite/jan_2.png': 'sprite/jan_2.png',
    'sprite/jan_3.png': 'sprite/jan_3.png',
    'sprite/jan_ball.png': 'sprite/jan_ball.png',
    'sprite/jan_ball2.png': 'sprite/jan_ball2.png',
    'sprite/jan_ball3.png': 'sprite/jan_ball3.png',
    'sprite/jan_chase.png': 'sprite/jan_chase.png',
    'sprite/jan_chaseb.png': 'sprite/jan_chaseb.png',
    'sprite/jan_chaseh.png': 'sprite/jan_chaseh.png',
    'sprite/jan_f.png': 'sprite/jan_f.png',
    'sprite/jan_s.png': 'sprite/jan_s.png',

    'sprite/firzen_0.png': 'sprite/firzen_0.png',
    'sprite/firzen_1.png': 'sprite/firzen_1.png',
    'sprite/firzen_2.png': 'sprite/firzen_2.png',
    'sprite/firzen_ball.png': 'sprite/firzen_ball.png',
    'sprite/firzen_chasef.png': 'sprite/firzen_chasef.png',
    'sprite/firzen_chasei.png': 'sprite/firzen_chasei.png',
    'sprite/firzen_up.png': 'sprite/firzen_up.png',
    'sprite/firzen_up2.png': 'sprite/firzen_up2.png',
    'sprite/firzen_up3.png': 'sprite/firzen_up3.png',
    'sprite/firzen_f.png': 'sprite/firzen_f.png',
    'sprite/firzen_s.png': 'sprite/firzen_s.png',

    'sprite/richter_0.png': 'sprite/richter_0.png',
    'sprite/richter_1.png': 'sprite/richter_1.png',
    'sprite/richter_2.png': 'sprite/richter_2.png',
    'sprite/richter_3.png': 'sprite/richter_3.png',
    'sprite/richter_ball.png': 'sprite/richter_ball.png',
    'sprite/richter_ball2.png': 'sprite/richter_ball2.png',
    'sprite/richter_f.png': 'sprite/richter_f.png',
    'sprite/richter_s.png': 'sprite/richter_s.png',

    'sprite/cl_0.png': 'sprite/cl_0.png',
    'sprite/cl_1.png': 'sprite/cl_1.png',
    'sprite/cl_2.png': 'sprite/cl_2.png',
    'sprite/cl_3.png': 'sprite/cl_3.png',
    'sprite/cl_ball.png': 'sprite/cl_ball.png',
    'sprite/cl_ball2.png': 'sprite/cl_ball2.png',
    'sprite/cl_chase.png': 'sprite/cl_chase.png',
    'sprite/cl_col.png': 'sprite/cl_col.png',
    'sprite/cl_col2.png': 'sprite/cl_col2.png',
    'sprite/cl_col3.png': 'sprite/cl_col3.png',
    'sprite/cl_col4.png': 'sprite/cl_col4.png',
    'sprite/cl_col5.png': 'sprite/cl_col5.png',
    'sprite/cl_flame.png': 'sprite/cl_flame.png',
    'sprite/cl_star.png': 'sprite/cl_star.png',
    'sprite/cl_star2.png': 'sprite/cl_star2.png',
    'sprite/cl_f.png': 'sprite/cl_f.png',
    'sprite/cl_s.png': 'sprite/cl_s.png',

    'sprite/justin_0.png': 'sprite/justin_0.png',
    'sprite/justin_0b.png': 'sprite/justin_0b.png',
    'sprite/justin_1.png': 'sprite/justin_1.png',
    'sprite/justin_1b.png': 'sprite/justin_1b.png',
    'sprite/justin_ball.png': 'sprite/justin_ball.png',
    'sprite/justin_col.png': 'sprite/justin_col.png',
    'sprite/justin_col2.png': 'sprite/justin_col2.png',
    'sprite/justin_f.png': 'sprite/justin_f.png',
    'sprite/justin_s.png': 'sprite/justin_s.png',

    'sprite/mark_0.png': 'sprite/mark_0.png',
    'sprite/mark_0b.png': 'sprite/mark_0b.png',
    'sprite/mark_1.png': 'sprite/mark_1.png',
    'sprite/mark_1b.png': 'sprite/mark_1b.png',
    'sprite/mark_f.png': 'sprite/mark_f.png',
    'sprite/mark_s.png': 'sprite/mark_s.png',

    'sprite/hunter_0.png': 'sprite/hunter_0.png',
    'sprite/hunter_0b.png': 'sprite/hunter_0b.png',
    'sprite/hunter_1.png': 'sprite/hunter_1.png',
    'sprite/hunter_1b.png': 'sprite/hunter_1b.png',
    'sprite/hunter_arrow1.png': 'sprite/hunter_arrow1.png',
    'sprite/hunter_arrow2.png': 'sprite/hunter_arrow2.png',
    'sprite/hunter_arrow3.png': 'sprite/hunter_arrow3.png',
    'sprite/hunter_col.png': 'sprite/hunter_col.png',
    'sprite/hunter_exp.png': 'sprite/hunter_exp.png',
    'sprite/hunter_f.png': 'sprite/hunter_f.png',
    'sprite/hunter_s.png': 'sprite/hunter_s.png',

    'sprite/jack_0.png': 'sprite/jack_0.png',
    'sprite/jack_0b.png': 'sprite/jack_0b.png',
    'sprite/jack_1.png': 'sprite/jack_1.png',
    'sprite/jack_1b.png': 'sprite/jack_1b.png',
    'sprite/jack_b.png': 'sprite/jack_b.png',
    'sprite/jack_b2.png': 'sprite/jack_b2.png',
    'sprite/jack_col.png': 'sprite/jack_col.png',
    'sprite/jack_col2.png': 'sprite/jack_col2.png',
    'sprite/jack_f.png': 'sprite/jack_f.png',
    'sprite/jack_s.png': 'sprite/jack_s.png',

    'sprite/sorcerer_0.png': 'sprite/sorcerer_0.png',
    'sprite/sorcerer_0b.png': 'sprite/sorcerer_0b.png',
    'sprite/sorcerer_1.png': 'sprite/sorcerer_1.png',
    'sprite/sorcerer_1b.png': 'sprite/sorcerer_1b.png',
    'sprite/sorcerer_ball.png': 'sprite/sorcerer_ball.png',
    'sprite/sorcerer_ball2.png': 'sprite/sorcerer_ball2.png',
    'sprite/sorcerer_w.png': 'sprite/sorcerer_w.png',
    'sprite/sorcerer_f.png': 'sprite/sorcerer_f.png',
    'sprite/sorcerer_s.png': 'sprite/sorcerer_s.png',

    'sprite/bat_0.png': 'sprite/bat_0.png',
    'sprite/bat_1.png': 'sprite/bat_1.png',
    'sprite/bat_2.png': 'sprite/bat_2.png',
    'sprite/bat_ball.png': 'sprite/bat_ball.png',
    'sprite/bat_ball2.png': 'sprite/bat_ball2.png',
    'sprite/bat_chase.png': 'sprite/bat_chase.png',
    'sprite/bat_chase2.png': 'sprite/bat_chase2.png',
    'sprite/bat_chase3.png': 'sprite/bat_chase3.png',
    'sprite/bat_chase4.png': 'sprite/bat_chase4.png',
    'sprite/bat_f.png': 'sprite/bat_f.png',
    'sprite/bat_s.png': 'sprite/bat_s.png',

    'sprite/bat2_0.png': 'sprite/bat2_0.png',
    'sprite/bat2_1.png': 'sprite/bat2_1.png',
    'sprite/bat2_2.png': 'sprite/bat2_2.png',
    'sprite/bat2_f.png': 'sprite/bat2_f.png',
    'sprite/bat2_s.png': 'sprite/bat2_s.png',

    'sprite/monk_0.png': 'sprite/monk_0.png',
    'sprite/monk_0b.png': 'sprite/monk_0b.png',
    'sprite/monk_1.png': 'sprite/monk_1.png',
    'sprite/monk_1b.png': 'sprite/monk_1b.png',
    'sprite/monk_ball.png': 'sprite/monk_ball.png',
    'sprite/monk_col.png': 'sprite/monk_col.png',
    'sprite/monk_col2.png': 'sprite/monk_col2.png',
    'sprite/monk_golden.png': 'sprite/monk_golden.png',
    'sprite/monk_f.png': 'sprite/monk_f.png',
    'sprite/monk_s.png': 'sprite/monk_s.png',

    'sprite/louisEX_0.png': 'sprite/louisEX_0.png',
    'sprite/louisEX_1.png': 'sprite/louisEX_1.png',
    'sprite/louisEX_2.png': 'sprite/louisEX_2.png',
    'sprite/louisEX_3.png': 'sprite/louisEX_3.png',
    'sprite/louisEX_4.png': 'sprite/louisEX_4.png',
    'sprite/louisEX_ball.png': 'sprite/louisEX_ball.png',
    'sprite/louisEX_ww.png': 'sprite/louisEX_ww.png',
    'sprite/louisEX_f.png': 'sprite/louisEX_f.png',
    'sprite/louisEX_s.png': 'sprite/louisEX_s.png',

    'sprite/guardian_0.png': 'sprite/guardian_0.png',
    'sprite/guardian_1.png': 'sprite/guardian_1.png',
    'sprite/guardian_2.png': 'sprite/guardian_2.png',
    'sprite/guardian_ball.png': 'sprite/guardian_ball.png',
    'sprite/guardian_f.png': 'sprite/guardian_f.png',
    'sprite/guardian_s.png': 'sprite/guardian_s.png',

    'sprite/criminal.png': 'sprite/criminal.png',

    'sprite/etc.png': 'sprite/etc.png',
    'sprite/sflash.png': 'sprite/sflash.png',
    'sprite/spark.png': 'sprite/spark.png',

    'sprite/weapon4.png': 'sprite/weapon4.png',
    'sprite/weapon5.png': 'sprite/weapon5.png',
    'sprite/weapon6.png': 'sprite/weapon6.png',
    'sprite/weapon7.png': 'sprite/weapon7.png',
    'sprite/weapon8.png': 'sprite/weapon8.png',
    'sprite/weapon9.png': 'sprite/weapon9.png',
    'sprite/weapon10.png': 'sprite/weapon10.png',
    'sprite/weapon11.png': 'sprite/weapon11.png',
    'sprite/weapon12.png': 'sprite/weapon12.png',
    'sprite/weapon13.png': 'sprite/weapon13.png'
  }
}
